imports:
    - { resource: 'packages/doctrine.yaml' }

sylius_grid:
    templates:
        action:
            create_product_variant_attribute: "@UmanitSyliusProductVariantAttributePlugin/Admin/ProductVariantAttribute/Grid/Action/create.html.twig"
    grids:
        umanit_sylius_product_variant_attribute_plugin_admin_product_variant_attribute:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product_variant_attribute.class%"
            sorting:
                position: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                position:
                    type: string
                    enabled: false
                    sortable: ~
                type:
                    type: twig
                    label: sylius.ui.type
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/label.html.twig"
            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create_product_variant_attribute
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
